name: Build application (Mac OS)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (vX.X.X)'
        required: True
        type: string
      mainfile:
        description: 'Main program file (DOES NOT END WITH .py)'
        required: True
        type: string

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install -r requirements.txt
        
    - name: Build app (Mac OS)
      run: |
        py2applet --make-setup ${{ format('{0}.py', env.MAINFILE) }}
        python setup.py py2app
        mv ${{ format('dist/{0}.app', env.MAINFILE) }} ${{ format('neonmobmatcher-{0}.app', env.TAG) }}
        7z a ${{ format('neonmobmatcher-{0}.app.zip', env.TAG) }} ${{ format('neonmobmatcher-{0}.app', env.TAG) }}
      env:
        TAG: ${{ github.event.inputs.tag }}
        MAINFILE: ${{ github.event.inputs.mainfile }}
    
    - name: Add binary to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{ format('neonmobmatcher-{0}.app.zip', env.TAG) }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.inputs.tag }}
      env:
        TAG: ${{ github.event.inputs.tag }}
